### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by winsontan520** [dawsonice/ProMosaic#1]
Thanks for the library, I found the library is very useful.
But I encounter out of memory issue when load image with size 3264x2448 (Photo take from samsung note 2)

```
12-23 16:52:28.498: E/AndroidRuntime(9394): FATAL EXCEPTION: main
12-23 16:52:28.498: E/AndroidRuntime(9394): Process: me.dawson.promosaic, PID: 9394
12-23 16:52:28.498: E/AndroidRuntime(9394): java.lang.OutOfMemoryError
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.graphics.Bitmap.nativeCreate(Native Method)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.graphics.Bitmap.createBitmap(Bitmap.java:754)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at me.dawson.promosaic.MosaicView.getGridMosaic(MosaicView.java:251)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at me.dawson.promosaic.MosaicView.getCoverLayer(MosaicView.java:209)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at me.dawson.promosaic.MosaicView.setSrcPath(MosaicView.java:162)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at me.dawson.promosaic.ProMosaic.onActivityResult(ProMosaic.java:174)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.app.Activity.dispatchActivityResult(Activity.java:5423)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.app.ActivityThread.deliverResults(ActivityThread.java:3378)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3425)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.app.ActivityThread.access$1300(ActivityThread.java:144)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1253)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.os.Handler.dispatchMessage(Handler.java:102)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.os.Looper.loop(Looper.java:136)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at android.app.ActivityThread.main(ActivityThread.java:5139)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at java.lang.reflect.Method.invokeNative(Native Method)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at java.lang.reflect.Method.invoke(Method.java:515)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
12-23 16:52:28.498: E/AndroidRuntime(9394):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lsjwzh** [comment]
That is not a problem caused by promosaic. 
The image is too large.

**Comment by winsontan520** [comment]
lsjwzh you are right. Got to scale down the image before load in canvas else low end device will crash due to out of memory.
